### PR TITLE
Add option to omit hashes when packaging poetry project

### PR DESCRIPTION
**Pull request by brent-moffit**
https://github.com/hmrc/python-aws-lambda-packager/issues/2

If your project has a dependency on a github depot lambda-packager throws an error during package creation. This prevents me from being able to use my own shared libraries as dependencies with lambda-packager.

Workaround to add an option to export your poetry dependencies without hashes.

### CODE REVIEW

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by cob16** [comment]
test this please

**Comment by cob16** [comment]
Hey sorry I don't follow this repo (perhaps I should) so only just saw your changes today. 
This looks like a good change and I am happy to merge it  :+1:  

One thing I would like to add is documenting this in the readme

(Note: I am just fixing the build in the background)

**Comment by cob16** [comment]
test this please

**Review by cob16 — APPROVED** [review]

**Comment by cob16** [comment]
@brent-moffit If you can give me access to your PR branch I will add the right doc changes (and co-sign the commits to allow merging)

For doc I was going to add the following:
<hr>

### Ignore hashes
Only has an effect when using poetry `pyproject.toml` files

Skips exporting hashes from poetry to avoid issues when using non-pypi packages 
by providing `--without-hashes` flag when calling `poetry export`
See https://github.com/hmrc/python-aws-lambda-packager/issues/2 for more info (Note: version number remains pinned when this is enabled)
```toml
without_hashes = True
```

**Comment by cob16** [comment]
going to merge this with your changes in another branch :+1:

**Comment by brent-moffit** [comment]
Thanks @cob16! My bad for slacking on notifications now.  I've added you as a collaborator on my fork if you still need access.  I have a few other changes in there that might be interesting to integrate but can open more independent PRs for that stuff.  Thanks for taking a look!

**Pull request closed without merging**
